<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;

class ClientsTableSeeder extends Seeder
{
    public function run()
    {
        $clients = [
            [
                'id' => 1,
                'first_name' => 'Client1',
                'last_name' => 'Test1',
                'date_of_birth' => '1983-02-02',
                'gender' => 'female',
                'mrn' => 1001,
                'carelon_id' => 'EshbqwMGLL',
                'medicaid_id' => 'jKi5Ts5A',
                'primary_diagnosis_code' => 'F81',
                'starting_date' => '2024-12-09',
                'discharge_date' => null,
                'group' => 'IOP',
                'ssn' => '203206420',
                'email' => 'client1@example.com',
                'phone' => '+14401291575',
                'status' => 'inactive',
                'address' => '123 Test Street, City 1',
                'notes' => 'This is a note for client 1',
                'bed_status' => 'unhoused',
                'apartment_id' => null,
                'created_at' => '2025-02-02 02:27:54',
                'updated_at' => '2025-02-02 02:27:54',
            ],
            [
                'id' => 2,
                'first_name' => 'Client2',
                'last_name' => 'Test2',
                'date_of_birth' => '2005-02-02',
                'gender' => 'prefer_not_to_say',
                'mrn' => 1002,
                'carelon_id' => 'Dh9jOSq6VQ',
                'medicaid_id' => 'OOkCn90G',
                'primary_diagnosis_code' => 'F43',
                'starting_date' => '2024-11-30',
                'discharge_date' => null,
                'group' => 'PHP',
                'ssn' => '855031473',
                'email' => 'client2@example.com',
                'phone' => '+12142479506',
                'status' => 'active',
                'address' => '123 Test Street, City 2',
                'notes' => 'This is a note for client 2',
                'bed_status' => 'unassigned',
                'apartment_id' => null,
                'created_at' => '2025-02-02 02:27:54',
                'updated_at' => '2025-02-02 02:27:54',
            ],
            [
                'id' => 3,
                'first_name' => 'Client3',
                'last_name' => 'Test3',
                'date_of_birth' => '1982-02-02',
                'gender' => 'female',
                'mrn' => 1003,
                'carelon_id' => 'GjzxIfwtFn',
                'medicaid_id' => 'IcXZSyzT',
                'primary_diagnosis_code' => 'F51',
                'starting_date' => '2025-01-06',
                'discharge_date' => null,
                'group' => 'PHP',
                'ssn' => '310890297',
                'email' => 'client3@example.com',
                'phone' => '+15657655598',
                'status' => 'active',
                'address' => '123 Test Street, City 3',
                'notes' => 'This is a note for client 3',
                'bed_status' => 'unassigned',
                'apartment_id' => null,
                'created_at' => '2025-02-02 02:27:54',
                'updated_at' => '2025-02-02 02:27:54',
            ],
            [
                'id' => 4,
                'first_name' => 'Client4',
                'last_name' => 'Test4',
                'date_of_birth' => '2001-02-02',
                'gender' => 'female',
                'mrn' => 1004,
                'carelon_id' => 'kOhxBsM6mX',
                'medicaid_id' => '1gDD5CKE',
                'primary_diagnosis_code' => 'F92',
                'starting_date' => '2025-01-11',
                'discharge_date' => NULL,
                'group' => 'PHP',
                'ssn' => '724971205',
                'email' => 'client4@example.com',
                'phone' => '+14856087107',
                'status' => 'active',
                'address' => '123 Test Street, City 4',
                'notes' => 'This is a note for client 4',
                'bed_status' => 'unassigned',
                'apartment_id' => NULL,
                'created_at' => '2025-02-02T02:27:54.000000Z',
                'updated_at' => '2025-02-02T02:27:54.000000Z',
            ],
            [
                'id' => 5,
                'first_name' => 'Client5',
                'last_name' => 'Test5',
                'date_of_birth' => '1976-02-02',
                'gender' => 'male',
                'mrn' => 1005,
                'carelon_id' => 'FEGzcgEU6F',
                'medicaid_id' => 'qGmXX965',
                'primary_diagnosis_code' => 'F28',
                'starting_date' => '2025-01-13',
                'discharge_date' => NULL,
                'group' => 'PHP',
                'ssn' => '350691063',
                'email' => 'client5@example.com',
                'phone' => '+12236390174',
                'status' => 'inactive',
                'address' => '123 Test Street, City 5',
                'notes' => 'This is a note for client 5',
                'bed_status' => 'unassigned',
                'apartment_id' => NULL,
                'created_at' => '2025-02-02T02:27:54.000000Z',
                'updated_at' => '2025-02-02T02:27:54.000000Z',
            ],
            [
                'id' => 6,
                'first_name' => 'Client6',
                'last_name' => 'Test6',
                'date_of_birth' => '2003-02-02',
                'gender' => 'female',
                'mrn' => 1006,
                'carelon_id' => 'oZBTJNSl2i',
                'medicaid_id' => '8D8pWoFd',
                'primary_diagnosis_code' => 'F75',
                'starting_date' => '2025-01-22',
                'discharge_date' => NULL,
                'group' => 'IOP',
                'ssn' => '372452202',
                'email' => 'client6@example.com',
                'phone' => '+11929832307',
                'status' => 'inactive',
                'address' => '123 Test Street, City 6',
                'notes' => 'This is a note for client 6',
                'bed_status' => 'unassigned',
                'apartment_id' => NULL,
                'created_at' => '2025-02-02T02:27:54.000000Z',
                'updated_at' => '2025-02-02T02:27:54.000000Z',
            ],
            [
                'id' => 7,
                'first_name' => 'Client7',
                'last_name' => 'Test7',
                'date_of_birth' => '1999-02-02',
                'gender' => 'male',
                'mrn' => 1007,
                'carelon_id' => 'XCGT1eceF9',
                'medicaid_id' => '0dufbmWz',
                'primary_diagnosis_code' => 'F34',
                'starting_date' => '2024-12-30',
                'discharge_date' => NULL,
                'group' => 'PHP',
                'ssn' => '296471759',
                'email' => 'client7@example.com',
                'phone' => '+17925595944',
                'status' => 'active',
                'address' => '123 Test Street, City 7',
                'notes' => 'This is a note for client 7',
                'bed_status' => 'unhoused',
                'apartment_id' => NULL,
                'created_at' => '2025-02-02T02:27:54.000000Z',
                'updated_at' => '2025-02-02T02:27:54.000000Z',
            ],
            [
                'id' => 8,
                'first_name' => 'Client8',
                'last_name' => 'Test8',
                'date_of_birth' => '1975-02-02',
                'gender' => 'male',
                'mrn' => 1008,
                'carelon_id' => 'Q12DCa9m2h',
                'medicaid_id' => 'nwkToKoo',
                'primary_diagnosis_code' => 'F55',
                'starting_date' => '2024-11-22',
                'discharge_date' => NULL,
                'group' => 'IOP',
                'ssn' => '878795974',
                'email' => 'client8@example.com',
                'phone' => '+19573331765',
                'status' => 'active',
                'address' => '123 Test Street, City 8',
                'notes' => 'This is a note for client 8',
                'bed_status' => 'unassigned',
                'apartment_id' => NULL,
                'created_at' => '2025-02-02T02:27:54.000000Z',
                'updated_at' => '2025-02-02T02:27:54.000000Z',
            ],
            [
                'id' => 9,
                'first_name' => 'Client9',
                'last_name' => 'Test9',
                'date_of_birth' => '1981-02-02',
                'gender' => 'male',
                'mrn' => 1009,
                'carelon_id' => 'xtoNGR0mrw',
                'medicaid_id' => 'bFRmsaqK',
                'primary_diagnosis_code' => 'F83',
                'starting_date' => '2024-11-11',
                'discharge_date' => NULL,
                'group' => 'IOP',
                'ssn' => '941892809',
                'email' => 'client9@example.com',
                'phone' => '+12466012628',
                'status' => 'inactive',
                'address' => '123 Test Street, City 9',
                'notes' => 'This is a note for client 9',
                'bed_status' => 'unassigned',
                'apartment_id' => NULL,
                'created_at' => '2025-02-02T02:27:54.000000Z',
                'updated_at' => '2025-02-02T02:27:54.000000Z',
            ],
            [
                'id' => 10,
                'first_name' => 'Client10',
                'last_name' => 'Test10',
                'date_of_birth' => '2004-02-02',
                'gender' => 'male',
                'mrn' => 1010,
                'carelon_id' => 'vMhbaoZhYo',
                'medicaid_id' => 'piUMFDMa',
                'primary_diagnosis_code' => 'F42',
                'starting_date' => '2025-01-22',
                'discharge_date' => NULL,
                'group' => 'PHP',
                'ssn' => '680301078',
                'email' => 'client10@example.com',
                'phone' => '+12512636530',
                'status' => 'active',
                'address' => '123 Test Street, City 10',
                'notes' => 'This is a note for client 10',
                'bed_status' => 'unassigned',
                'apartment_id' => NULL,
                'created_at' => '2025-02-02T02:27:54.000000Z',
                'updated_at' => '2025-02-02T02:27:54.000000Z',
            ]
        ];

        foreach ($clients as $client) {
            Client::updateOrCreate(['id' => $client['id']], $client);
        }
    }
}
